"""Numerical tools for subset-state entanglement experiments."""

from .peak_fitting import local_m_grid, quadratic_peak_fit
from .tables import PEAK_M, PEAK_S, TABLE_I_PEAKS, read_table_i, table_i_array
from .core import (
    average_entropy_lower_bound_from_purity,
    balanced_bipartitions,
    dense_bulk_approximation,
    dnm_approximation,
    entropy_from_state_vector,
    fixed_cardinality_average_purity,
    entropy_from_support,
    exact_page_entropy_bits,
    fixed_cardinality_mean_spectrum,
    hypergeometric_occupancy_approximation,
    matrix_from_state_vector,
    matrix_from_support,
    mean_matrix_uniform_eigenvalue,
    natural_right_bits,
    omega_prime_factors_sieve,
    qft_state_from_support,
    random_balanced_partition,
    random_subset,
    renyi_entropy_from_spectrum,
    residue_class_entropy_ceiling,
    spectrum_from_matrix,
    summary_stats,
    tnm_approximation,
)

__all__ = [
    "PEAK_M",
    "PEAK_S",
    "TABLE_I_PEAKS",
    "local_m_grid",
    "quadratic_peak_fit",
    "read_table_i",
    "table_i_array",
    "average_entropy_lower_bound_from_purity",
    "balanced_bipartitions",
    "dense_bulk_approximation",
    "dnm_approximation",
    "entropy_from_state_vector",
    "fixed_cardinality_average_purity",
    "entropy_from_support",
    "exact_page_entropy_bits",
    "fixed_cardinality_mean_spectrum",
    "hypergeometric_occupancy_approximation",
    "matrix_from_state_vector",
    "matrix_from_support",
    "mean_matrix_uniform_eigenvalue",
    "natural_right_bits",
    "omega_prime_factors_sieve",
    "qft_state_from_support",
    "random_balanced_partition",
    "random_subset",
    "renyi_entropy_from_spectrum",
    "residue_class_entropy_ceiling",
    "spectrum_from_matrix",
    "summary_stats",
    "tnm_approximation",
]
